### ISSUE TITLE
Offline download version not working

### ISSUE THREAD

**Issue by UnnormalPerson** [lDEVinux/eaglercraft#2]
I was just checking on my laptop whether if I could download but when I left click the link, file not there, right click, file not on server.

**Comment by wxnnvs** [comment]
> I was just checking on my laptop whether if I could download but when I left click the link, file not there, right click, file not on server.

[www.xinix.space](https://xinix.space/1.8/offline)

**Comment by wxnnvs** [comment]
Nvm you search for 1.5.2 right?

**Comment by UnnormalPerson** [comment]
??? What- I thought 1.8.8 wait ok tks

**Comment by wxnnvs** [comment]
i got 1.8 offline download
https://xinix.space/1.8/offline

**Comment by UnnormalPerson** [comment]
I know I downloaded that already thanks! But um, how to make your own wss server???

**Comment by MeeladProE1** [comment]
I don't know???
